<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_Payment_Processor',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_Payment_Processor',
        'label' => E::ts('Dataro Payment Processor'),
        'api_entity' => 'PaymentProcessor',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'description',
            'is_active',
            'billing_mode',
            'is_recur',
            'payment_type',
            'payment_instrument_id:label',
            'name',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_Payment_Processor_SearchDisplay_DataroPaymentProcessor',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroPaymentProcessor',
        'label' => E::ts('Dataro Payment Processor'),
        'saved_search_id.name' => 'Dataro_Payment_Processor',
        'type' => 'entity',
        'settings' => [
          'sort' => [
            [
              'id',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Processor ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'label' => E::ts('Backend Title'),
              'spec' => [
                'name' => 'title',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'title',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'dataType' => 'String',
              'label' => E::ts('Description'),
              'spec' => [
                'name' => 'description',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'description',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled'),
              'spec' => [
                'name' => 'is_active',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_active',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'billing_mode',
              'dataType' => 'Integer',
              'label' => E::ts('Processor Billing Mode'),
              'spec' => [
                'name' => 'billing_mode',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'billing_mode',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_recur',
              'dataType' => 'Boolean',
              'label' => E::ts('Processor Supports Recurring?'),
              'spec' => [
                'name' => 'is_recur',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_recur',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_type',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Type'),
              'spec' => [
                'name' => 'payment_type',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'payment_type',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Method'),
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Machine Name'),
              'spec' => [
                'name' => 'name',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'name',
                'original_field_entity' => 'PaymentProcessor',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
