<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_Contribution',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_Contribution',
        'label' => E::ts('Dataro Contribution'),
        'api_entity' => 'Contribution',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'contact_id',
            'total_amount',
            'financial_type_id:label',
            'contribution_page_id:label',
            'payment_instrument_id:label',
            'receive_date',
            'fee_amount',
            'net_amount',
            'trxn_id',
            'invoice_number',
            'cancel_date',
            'cancel_reason',
            'contribution_recur_id',
            'contribution_status_id:label',
            'address_id',
            'campaign_id:label',
            'tax_amount',
            'revenue_recognition_date',
            'receipt_date',
            'source',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_Contribution_SearchDisplay_DataroContribution',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroContribution',
        'label' => E::ts('Dataro Contribution'),
        'saved_search_id.name' => 'Dataro_Contribution',
        'type' => 'entity',
        'settings' => [
          'sort' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Contribution ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contact_id',
              'dataType' => 'Integer',
              'label' => E::ts('Contact ID'),
              'spec' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => 'Contact',
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'total_amount',
              'dataType' => 'Money',
              'label' => E::ts('Total Amount'),
              'spec' => [
                'name' => 'total_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'total_amount',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Financial Type'),
              'spec' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'FinancialType',
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_page_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Contribution Page'),
              'spec' => [
                'name' => 'contribution_page_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'ContributionPage',
                'original_field_name' => 'contribution_page_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Method'),
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receive_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Contribution Date'),
              'spec' => [
                'name' => 'receive_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'receive_date',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'fee_amount',
              'dataType' => 'Money',
              'label' => E::ts('Fee Amount'),
              'spec' => [
                'name' => 'fee_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'fee_amount',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'net_amount',
              'dataType' => 'Money',
              'label' => E::ts('Net Amount'),
              'spec' => [
                'name' => 'net_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'net_amount',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'trxn_id',
              'dataType' => 'String',
              'label' => E::ts('Transaction ID'),
              'spec' => [
                'name' => 'trxn_id',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'trxn_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'invoice_number',
              'dataType' => 'String',
              'label' => E::ts('Invoice Number'),
              'spec' => [
                'name' => 'invoice_number',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'invoice_number',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'cancel_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Cancelled / Refunded Date'),
              'spec' => [
                'name' => 'cancel_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'cancel_date',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'cancel_reason',
              'dataType' => 'Text',
              'label' => E::ts('Cancellation / Refund Reason'),
              'spec' => [
                'name' => 'cancel_reason',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'cancel_reason',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_recur_id',
              'dataType' => 'Integer',
              'label' => E::ts('Recurring Contribution'),
              'spec' => [
                'name' => 'contribution_recur_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => 'ContributionRecur',
                'original_field_name' => 'contribution_recur_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Contribution Status'),
              'spec' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'address_id',
              'dataType' => 'Integer',
              'label' => E::ts('Address'),
              'spec' => [
                'name' => 'address_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => 'Address',
                'original_field_name' => 'address_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'campaign_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Campaign'),
              'spec' => [
                'name' => 'campaign_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'Campaign',
                'original_field_name' => 'campaign_id',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'tax_amount',
              'dataType' => 'Money',
              'label' => E::ts('Tax Amount'),
              'spec' => [
                'name' => 'tax_amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'tax_amount',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'revenue_recognition_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Revenue Recognition Date'),
              'spec' => [
                'name' => 'revenue_recognition_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'revenue_recognition_date',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'receipt_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Receipt Date'),
              'spec' => [
                'name' => 'receipt_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'receipt_date',
                'original_field_entity' => 'Contribution',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'source',
              'dataType' => 'String',
              'label' => E::ts('Contribution Source'),
              'spec' => [
                'name' => 'source',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'source',
                'original_field_entity' => 'Contribution',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
