<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_Campaign',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_Campaign',
        'label' => E::ts('Dataro Campaign'),
        'api_entity' => 'Campaign',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'name',
            'title',
            'campaign_type_id:label',
            'description',
            'start_date',
            'end_date',
            'is_active',
            'status_id:label',
            'external_identifier',
            'parent_id',
            'created_date',
            'last_modified_date',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_Campaign_SearchDisplay_DataroCampaign',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroCampaign',
        'label' => E::ts('Dataro Campaign'),
        'saved_search_id.name' => 'Dataro_Campaign',
        'type' => 'entity',
        'settings' => [
          'sort' => [
            [
              'id',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Name'),
              'spec' => [
                'name' => 'name',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'name',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'title',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'spec' => [
                'name' => 'title',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'title',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'campaign_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Type'),
              'spec' => [
                'name' => 'campaign_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'campaign_type_id',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'dataType' => 'Text',
              'label' => E::ts('Description'),
              'spec' => [
                'name' => 'description',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'description',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Start Date'),
              'spec' => [
                'name' => 'start_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'start_date',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('End Date'),
              'spec' => [
                'name' => 'end_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'end_date',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled'),
              'spec' => [
                'name' => 'is_active',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_active',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Status'),
              'spec' => [
                'name' => 'status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'status_id',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'external_identifier',
              'dataType' => 'String',
              'label' => E::ts('External ID'),
              'spec' => [
                'name' => 'external_identifier',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'external_identifier',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'parent_id',
              'dataType' => 'Integer',
              'label' => E::ts('Parent Campaign ID'),
              'spec' => [
                'name' => 'parent_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => 'Campaign',
                'original_field_name' => 'parent_id',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'created_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Created Date'),
              'spec' => [
                'name' => 'created_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'created_date',
                'original_field_entity' => 'Campaign',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'last_modified_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Campaign Modified Date'),
              'spec' => [
                'name' => 'last_modified_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'last_modified_date',
                'original_field_entity' => 'Campaign',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
