<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_ContributionRecur',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_ContributionRecur',
        'label' => E::ts('Dataro Recurring Contribution'),
        'api_entity' => 'ContributionRecur',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'contact_id',
            'financial_type_id:label',
            'start_date',
            'end_date',
            'next_sched_contribution_date',
            'amount',
            'frequency_unit:label',
            'frequency_interval',
            'installments',
            'create_date',
            'modified_date',
            'trxn_id',
            'invoice_id',
            'contribution_status_id:label',
            'payment_processor_id:label',
            'payment_instrument_id:label',
            'campaign_id:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_ContributionRecur_SearchDisplay_DataroContributionRecur',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroContributionRecur',
        'label' => E::ts('Dataro Recurring Contribution'),
        'saved_search_id.name' => 'Dataro_ContributionRecur',
        'type' => 'entity',
        'settings' => [
          'sort' => [
            [
              'id',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Recurring Contribution ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contact_id',
              'dataType' => 'Integer',
              'label' => E::ts('Contact ID'),
              'spec' => [
                'name' => 'contact_id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => 'Contact',
                'original_field_name' => 'contact_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'financial_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Financial Type'),
              'spec' => [
                'name' => 'financial_type_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'FinancialType',
                'original_field_name' => 'financial_type_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Start Date'),
              'spec' => [
                'name' => 'start_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'start_date',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Recurring Contribution End Date'),
              'spec' => [
                'name' => 'end_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'end_date',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'next_sched_contribution_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Next Scheduled Contribution Date'),
              'spec' => [
                'name' => 'next_sched_contribution_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'next_sched_contribution_date',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'amount',
              'dataType' => 'Money',
              'label' => E::ts('Amount'),
              'spec' => [
                'name' => 'amount',
                'data_type' => 'Money',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'amount',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'frequency_unit:label',
              'dataType' => 'String',
              'label' => E::ts('Frequency Unit'),
              'spec' => [
                'name' => 'frequency_unit',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'frequency_unit',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'frequency_interval',
              'dataType' => 'Integer',
              'label' => E::ts('Interval (number of units)'),
              'spec' => [
                'name' => 'frequency_interval',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'frequency_interval',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'installments',
              'dataType' => 'Integer',
              'label' => E::ts('Number of Installments'),
              'spec' => [
                'name' => 'installments',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'installments',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'create_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Created Date'),
              'spec' => [
                'name' => 'create_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'create_date',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'modified_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Modified Date'),
              'spec' => [
                'name' => 'modified_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'modified_date',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'trxn_id',
              'dataType' => 'String',
              'label' => E::ts('Transaction ID'),
              'spec' => [
                'name' => 'trxn_id',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'trxn_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'invoice_id',
              'dataType' => 'String',
              'label' => E::ts('Invoice ID'),
              'spec' => [
                'name' => 'invoice_id',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'invoice_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contribution_status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Status'),
              'spec' => [
                'name' => 'contribution_status_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'contribution_status_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_processor_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Processor'),
              'spec' => [
                'name' => 'payment_processor_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'PaymentProcessor',
                'original_field_name' => 'payment_processor_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'payment_instrument_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Payment Method'),
              'spec' => [
                'name' => 'payment_instrument_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'payment_instrument_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'campaign_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Campaign'),
              'spec' => [
                'name' => 'campaign_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'Campaign',
                'original_field_name' => 'campaign_id',
                'original_field_entity' => 'ContributionRecur',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
