<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_Option_Value',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_Option_Value',
        'label' => E::ts('Dataro Option Value'),
        'api_entity' => 'OptionValue',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'label',
            'description',
            'is_active',
            'option_group_id:label',
            'name',
            'filter',
            'value',
            'grouping',
          ],
          'orderBy' => [],
          'where' => [
            [
              'option_group_id:name',
              'IN',
              [
                'contribution_status',
                'activity_status',
                'contribution_recur_status',
                'campaign_type',
                'campaign_status',
                'activity_type',
                'payment_instrument',
                'phone_type',
                'contract_cancel_reason',
                'activity_contacts',
                'dataro_model_name',
              ],
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_Option_Value_SearchDisplay_DataroOptionValue',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroOptionValue',
        'label' => E::ts('Dataro Option Value'),
        'saved_search_id.name' => 'Dataro_Option_Value',
        'type' => 'entity',
        'settings' => [
          'sort' => [
            [
              'id',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Option Value ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'label',
              'dataType' => 'String',
              'label' => E::ts('Option Label'),
              'spec' => [
                'name' => 'label',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'label',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'dataType' => 'Text',
              'label' => E::ts('Option Description'),
              'spec' => [
                'name' => 'description',
                'data_type' => 'Text',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'description',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Enabled'),
              'spec' => [
                'name' => 'is_active',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_active',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'option_group_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Option Group'),
              'spec' => [
                'name' => 'option_group_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => 'OptionGroup',
                'original_field_name' => 'option_group_id',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Option Name'),
              'spec' => [
                'name' => 'name',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'name',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'filter',
              'dataType' => 'Integer',
              'label' => E::ts('Filter'),
              'spec' => [
                'name' => 'filter',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'filter',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'value',
              'dataType' => 'String',
              'label' => E::ts('Option Value'),
              'spec' => [
                'name' => 'value',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'value',
                'original_field_entity' => 'OptionValue',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'grouping',
              'dataType' => 'String',
              'label' => E::ts('Option Grouping Name'),
              'spec' => [
                'name' => 'grouping',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'grouping',
                'original_field_entity' => 'OptionValue',
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
