<?php

use CRM_Dataro_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Dataro_Contact',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Dataro_Contact',
        'label' => E::ts('Dataro Contact'),
        'api_entity' => 'Contact',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'external_identifier',
            'is_deleted',
            'created_date',
            'contact_type:label',
            'gender_id:label',
            'birth_date',
            'is_deceased',
            'deceased_date',
            'modified_date',
            'first_name',
            'ISNULL(last_name) AS ISNULL_last_name',
          ],
          'orderBy' => [],
          'where' => [
            [
              'OR',
              [
                [
                  'is_deleted',
                  '=',
                  TRUE,
                ],
                [
                  'is_deleted',
                  '=',
                  FALSE,
                ],
              ],
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Dataro_Contact_SearchDisplay_DataroContact',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'never',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'DataroContact',
        'label' => E::ts('Dataro Contact'),
        'saved_search_id.name' => 'Dataro_Contact',
        'type' => 'entity',
        'settings' => [
          'sort' => [
            [
              'id',
              'ASC',
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('Contact ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'external_identifier',
              'dataType' => 'String',
              'label' => E::ts('External Identifier'),
              'spec' => [
                'name' => 'external_identifier',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'external_identifier',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_deleted',
              'dataType' => 'Boolean',
              'label' => E::ts('Contact is in Trash'),
              'spec' => [
                'name' => 'is_deleted',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_deleted',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'created_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Created Date'),
              'spec' => [
                'name' => 'created_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'created_date',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'contact_type:label',
              'dataType' => 'String',
              'label' => E::ts('Contact Type'),
              'spec' => [
                'name' => 'contact_type',
                'data_type' => 'String',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'contact_type',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'gender_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Gender'),
              'spec' => [
                'name' => 'gender_id',
                'data_type' => 'Integer',
                'suffixes' => [
                  'id',
                  'label',
                ],
                'options' => TRUE,
                'fk_entity' => NULL,
                'original_field_name' => 'gender_id',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'birth_date',
              'dataType' => 'Date',
              'label' => E::ts('Birth Date'),
              'spec' => [
                'name' => 'birth_date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'birth_date',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'is_deceased',
              'dataType' => 'Boolean',
              'label' => E::ts('Is Deceased'),
              'spec' => [
                'name' => 'is_deceased',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'is_deceased',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'deceased_date',
              'dataType' => 'Date',
              'label' => E::ts('Deceased Date'),
              'spec' => [
                'name' => 'deceased_date',
                'data_type' => 'Date',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'deceased_date',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'modified_date',
              'dataType' => 'Timestamp',
              'label' => E::ts('Modified Date'),
              'spec' => [
                'name' => 'modified_date',
                'data_type' => 'Timestamp',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'modified_date',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'first_name',
              'dataType' => 'String',
              'label' => E::ts('First Name'),
              'spec' => [
                'name' => 'first_name',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'fk_entity' => NULL,
                'original_field_name' => 'first_name',
                'original_field_entity' => 'Contact',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'ISNULL_last_name',
              'dataType' => 'Boolean',
              'label' => E::ts('(Is null) Last Name'),
              'spec' => [
                'name' => 'ISNULL_last_name',
                'data_type' => 'Boolean',
                'suffixes' => NULL,
                'options' => FALSE,
              ],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];
