-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_dataro_score`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_dataro_score
-- *
-- * Dataro Propensity Scores
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dataro_score` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DataroScore ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `model_name_id` int unsigned NOT NULL COMMENT 'ID of model name',
  `model_score` decimal(7,6) NULL COMMENT 'Propensity Score',
  `model_rank` int unsigned NULL COMMENT 'Propensity Rank',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_unique_contact_id_model_name_id`(contact_id, model_name_id),
  CONSTRAINT FK_civicrm_dataro_score_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
